### ISSUE TITLE
Hi, i7/ 16gb /256G/ Iris 540  適用嗎？

### ISSUE THREAD

**Issue by deadfoxwang** [bigsadan/surface-pro-4-hackintosh-10.14.3#10]
Hi, 
請問 i7/ 16gb /256G/ Iris 540  適用嗎？

一直卡在黑色屏幕，中間白色APPLE logo

**Comment by bigsadan** [comment]
clover中自行调整下试试，AAPL,ig-platform-id 改成适合540的，机型设置里更改内存信息设置，我的是8G（4GX2)，你可以按自己的配置修改一下。

**Comment by deadfoxwang** [comment]
[...]
root device uuid is xxxx
End InitBootStruct
Start and End LoadRAMDisk
Start FinalizeBootStruct
Start and End RandomSeed
++++++++++++++++++++++++++++++++++++++++++++

一直卡在這裏， 内存信息應該怎麽改呀？ 我的是 16G ， 我改成 16X1  、  8X2 都不行。。。

**Comment by deadfoxwang** [comment]
![image](https://user-images.githubusercontent.com/12786379/60641668-5e23d880-9e5f-11e9-9ca9-286c60158e43.png)
![image](https://user-images.githubusercontent.com/12786379/60641682-6ed44e80-9e5f-11e9-9905-12fba61e9dbd.png)
![image](https://user-images.githubusercontent.com/12786379/60641698-78f64d00-9e5f-11e9-90eb-a06666b62fee.png)

**Comment by bigsadan** [comment]
你这个就是8GX2。。卡+++号基本上都是DRIVER64UEFI中EFI文件造成的，删除掉内存相关的EFI文件通常就可以通过了。

**Comment by deadfoxwang** [comment]
非常感謝你的幫助。

**Comment by deadfoxwang** [comment]
不好意思， 還有兩個問題想咨詢一下。
1. 安裝完成后也一直需要 config sp4-install.plist 才能啓動， 如果 換回config.plist ，就會一直重啓。
2. RDM ， 我按照操作走了一遍，也重啓了，但是還是無法改變分辨率， 一直是2736 * 1824 ， 很卡很小。
